version: '3.8'

services:
  shantagent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: shantagent:latest
    container_name: shantagent
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ../chatbot.db:/app/chatbot.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - shantagent-network

networks:
  shantagent-network:
    driver: bridge